# fm.py
# Convert DX7 patches -- including .syx sysex files -- into AMY patches.
#
# Runs everywhere AMY's Python does, including MicroPython (Tulip, AMYboard,
# web): no numpy, no dataclasses. The quickest way in is load_syx(), which
# takes the bytes (or a base64 string) of a DX7 sysex bank or voice and
# stores it as an AMY user patch you can hand to a synth:
#
#   import amy
#   from amy import fm
#   name = fm.load_syx(open('MYBANK.SYX','rb').read(), voice=3, patch=1024)
#   amy.send(synth=1, num_voices=6, patch=1024)   # play it on MIDI synth 1
#
# Accepted inputs: a 4104-byte 32-voice bank sysex (the usual .SYX file),
# a 163-byte single-voice VCED sysex, raw packed (128-byte) or unpacked
# (155/156-byte) voice data, or a base64 string of any of those.

import math
import amy

_LOG2 = 0.6931471805599453


class DX7Operator:
    """Per-operator parameters for DX7 patches."""
    def __init__(self, opnum=0):
        self.opnum = opnum
        self.rates = None    # 4
        self.levels = None   # 4
        self.breakpoint = 0
        self.bp_depths = None  # 2
        self.bp_curves = None  # 2
        self.kbdratescaling = 0
        self.ampmodsens = 0
        self.keyvelsens = 0
        self.ratiotuning = False
        self.freq_coarse = 0
        self.freq_fine = 0
        self.freq_detune = 0
        self.opamp = 0


class DX7Patch:
    """Encapsulates information in a DX7 Patch."""
    def __init__(self):
        self.ops = None          # 6 DX7Operators
        self.pitch_rates = None  # 4
        self.pitch_levels = None # 4
        self.algo = 0  # 1-32
        self.feedback = 0
        self.oscsync = 0
        self.lfospeed = 0
        self.lfodelay = 0
        self.lfopitchmoddepth = 0
        self.lfoampmoddepth = 0
        self.lfosync = 0
        self.lfowaveform = 0
        self.pitchmodsens = 0
        self.transpose = 0
        self.name = ""

    @staticmethod
    def from_patch_number(patch_number):
        # returns a patch (as in patches.h) from
        # default-dx7-patches.bin generated by dx7db, see https://github.com/bwhitman/learnfm
        f = bytes(open("amy/default-dx7-patches.bin", mode="rb").read())
        patch_data = f[patch_number*156:patch_number*156+156]
        return DX7Patch.from_bytestream(bytearray(patch_data))

    @staticmethod
    def from_syx(data, voice=0):
        """Parse a DX7 sysex (.syx) file, bank or single voice, into a DX7Patch.

        data can be the bytes of a 32-voice bank sysex (4104 bytes), a
        single-voice VCED sysex (163 bytes), raw packed (128 byte) or
        unpacked (155/156 byte) voice data, or a base64 str of any of those.
        voice picks the voice (0-31) when data holds a bank."""
        kind, payload = _syx_payload(data)
        if kind == 'bank':
            if voice < 0 or voice > 31:
                raise ValueError('bank voice must be 0-31')
            return DX7Patch.from_bytestream(
                unpack_packed_voice(payload[voice*128:(voice+1)*128]))
        return DX7Patch.from_bytestream(payload)

    @staticmethod
    def from_bytestream(bytestream):
        """Simply reformat the bytestream into parameters."""
        result = DX7Patch()

        bytestream = bytes(bytestream)
        byteno = 0

        def nextbyte(count=1):
            nonlocal byteno
            if count > 1:
                # Return a list.
                return [nextbyte() for _ in range(count)]
            b = bytestream[byteno]
            byteno += 1
            # Return a bare byte.
            return b

        ops = []
        # Starts at op 6
        for i in range(6, 0, -1):
            op = DX7Operator(opnum=i)
            op.rates = nextbyte(4)
            op.levels = nextbyte(4)
            op.breakpoint = nextbyte()
            op.bp_depths = nextbyte(2)
            op.bp_curves = nextbyte(2)
            op.kbdratescaling = nextbyte()
            op.ampmodsens = nextbyte()
            op.keyvelsens = nextbyte()
            op.opamp = nextbyte()
            op.ratiotuning = False if nextbyte() == 1 else True
            op.freq_coarse = nextbyte()
            op.freq_fine = nextbyte()
            op.freq_detune = nextbyte()
            ops.append(op)
        result.ops = ops
        result.pitch_rates = nextbyte(4)
        result.pitch_levels = nextbyte(4)
        result.algo = 1 + nextbyte()
        result.feedback = nextbyte()
        result.oscsync = nextbyte()
        result.lfospeed = nextbyte()
        result.lfodelay = nextbyte()
        result.lfopitchmoddepth = nextbyte()
        result.lfoampmoddepth = nextbyte()
        result.lfosync = nextbyte()
        result.lfowaveform = nextbyte()
        result.pitchmodsens = nextbyte()
        result.transpose = nextbyte()
        result.name =  ''.join(chr(i) for i in nextbyte(10))
        return result

    def get_bytestream(self):
        """Convert a decoded patch dict back to a bytestream."""
        bytestream = []
        for op in self.ops:
            # Assume ordering is right in ops list.
            bytestream.extend(op.rates)
            bytestream.extend(op.levels)
            bytestream.append(op.breakpoint)
            bytestream.extend(op.bp_depths)
            bytestream.extend(op.bp_curves)
            bytestream.append(op.kbdratescaling)
            bytestream.append(op.ampmodsens)
            bytestream.append(op.keyvelsens)
            bytestream.append(op.opamp)
            bytestream.append(0 if op.ratiotuning else 1)
            bytestream.append(op.freq_coarse)
            bytestream.append(op.freq_fine)
            bytestream.append(op.freq_detune)
        bytestream.extend(self.pitch_rates)
        bytestream.extend(self.pitch_levels)
        bytestream.append(self.algo - 1)
        bytestream.append(self.feedback)
        bytestream.append(self.oscsync)
        bytestream.append(self.lfospeed)
        bytestream.append(self.lfodelay)
        bytestream.append(self.lfopitchmoddepth)
        bytestream.append(self.lfoampmoddepth)
        bytestream.append(self.lfosync)
        bytestream.append(self.lfowaveform)
        bytestream.append(self.pitchmodsens)
        bytestream.append(self.transpose)
        bytestream.extend(ord(c) for c in self.name)
        return bytes(bytestream)


def unpack_packed_voice(packed):
    """Expand one 128-byte packed (VMEM) voice into 155 unpacked (VCED) bytes."""
    packed = bytes(packed)
    if len(packed) != 128:
        raise ValueError('packed voice must be 128 bytes, got %d' % len(packed))
    out = []
    for o in range(6):
        p = packed[o*17:(o+1)*17]
        out.extend(p[0:4])           # EG rates
        out.extend(p[4:8])           # EG levels
        out.append(p[8])             # breakpoint
        out.append(p[9])             # left depth
        out.append(p[10])            # right depth
        out.append(p[11] & 3)        # left curve
        out.append((p[11] >> 2) & 3) # right curve
        out.append(p[12] & 7)        # kbd rate scaling
        out.append(p[13] & 3)        # amp mod sens
        out.append((p[13] >> 2) & 7) # key vel sens
        out.append(p[14])            # output level
        out.append(p[15] & 1)        # mode: 0 ratio, 1 fixed
        out.append((p[15] >> 1) & 31)# freq coarse
        out.append(p[16])            # freq fine
        out.append((p[12] >> 3) & 15)# detune
    g = packed[102:128]
    out.extend(g[0:4])            # pitch EG rates
    out.extend(g[4:8])            # pitch EG levels
    out.append(g[8] & 31)         # algorithm
    out.append(g[9] & 7)          # feedback
    out.append((g[9] >> 3) & 1)   # osc key sync
    out.append(g[10])             # LFO speed
    out.append(g[11])             # LFO delay
    out.append(g[12])             # LFO pitch mod depth
    out.append(g[13])             # LFO amp mod depth
    out.append(g[14] & 1)         # LFO key sync
    out.append((g[14] >> 1) & 7)  # LFO waveform
    out.append((g[14] >> 4) & 7)  # pitch mod sens
    out.append(g[15])             # transpose
    out.extend(g[16:26])          # name
    return bytes(out)


def pack_packed_voice(vced):
    """Compress one 155-byte unpacked (VCED) voice into 128 packed (VMEM) bytes."""
    v = bytes(vced)
    if len(v) < 155:
        raise ValueError('unpacked voice must be 155 bytes, got %d' % len(v))
    out = []
    for o in range(6):
        p = v[o*21:(o+1)*21]
        out.extend(p[0:11])                            # rates, levels, bp, depths
        out.append((p[11] & 3) | ((p[12] & 3) << 2))   # LC | RC<<2
        out.append((p[13] & 7) | ((p[20] & 15) << 3))  # RS | DET<<3
        out.append((p[14] & 3) | ((p[15] & 7) << 2))   # AMS | KVS<<2
        out.append(p[16])                              # output level
        out.append((p[17] & 1) | ((p[18] & 31) << 1))  # mode | coarse<<1
        out.append(p[19])                              # fine
    g = v[126:155]
    out.extend(g[0:8])                                 # pitch EG
    out.append(g[8] & 31)                              # algorithm
    out.append((g[9] & 7) | ((g[10] & 1) << 3))        # FB | OKS<<3
    out.extend(g[11:15])                               # LFO speed/delay/PMD/AMD
    out.append((g[15] & 1) | ((g[16] & 7) << 1) | ((g[17] & 7) << 4))  # LKS|LFW<<1|LPMS<<4
    out.append(g[18])                                  # transpose
    out.extend(g[19:29])                               # name
    return bytes(out)


def make_bank_syx(voices):
    """Build a 32-voice DX7 bank sysex from a list of packed or unpacked voices."""
    if len(voices) > 32:
        raise ValueError('a DX7 bank holds at most 32 voices')
    packed = []
    for v in voices:
        v = bytes(v)
        packed.append(v if len(v) == 128 else pack_packed_voice(v))
    packed.extend([packed[-1]] * (32 - len(packed)))  # pad short banks
    data = b''.join(packed)
    checksum = (128 - (sum(data) & 0x7F)) & 0x7F
    return bytes([0xF0, 0x43, 0x00, 0x09, 0x20, 0x00]) + data + bytes([checksum, 0xF7])


def _syx_payload(data):
    """Reduce sysex/base64/raw voice data to ('bank', 4096 bytes) or ('voice', VCED bytes)."""
    if isinstance(data, str):
        import binascii
        data = binascii.a2b_base64(''.join(data.split()))
    data = bytes(data)
    if len(data) and data[0] == 0xF0:
        if len(data) < 7 or data[1] != 0x43:
            raise ValueError('not a Yamaha sysex message')
        fmt = data[3]
        payload = data[6:-2]  # strip 6-byte header, checksum and F7
        checksum = (128 - (sum(payload) & 0x7F)) & 0x7F
        if checksum != data[-2] and amy.show_warnings:
            print('Warning: DX7 sysex checksum mismatch (got %d, expected %d)'
                  % (data[-2], checksum))
        if fmt == 9 and len(payload) == 4096:   # 32-voice packed bank
            return ('bank', payload)
        if fmt == 0 and len(payload) == 155:    # single-voice VCED
            return ('voice', payload)
        raise ValueError('unsupported DX7 sysex (format %d, %d byte payload)'
                         % (fmt, len(payload)))
    if len(data) == 4096:
        return ('bank', data)
    if len(data) == 128:
        return ('voice', unpack_packed_voice(data))
    if len(data) in (155, 156):
        return ('voice', data[:155])
    raise ValueError('unrecognized DX7 data (%d bytes)' % len(data))


def syx_names(data):
    """Return the list of voice names in a DX7 sysex bank (or single voice)."""
    kind, payload = _syx_payload(data)
    if kind == 'voice':
        return [''.join(chr(c) for c in payload[145:155])]
    return [''.join(chr(c) for c in payload[v*128+118:v*128+128]) for v in range(32)]


def load_syx(data, voice=0, patch=1024):
    """Store a voice from DX7 sysex data as AMY user patch number `patch`.

    data: bytes of a .SYX file (32-voice bank or single voice), raw voice
    data, or a base64 string of any of those. voice: which voice (0-31) to
    use when data is a bank. Returns the voice's name. After loading, play
    it with e.g. amy.send(synth=1, num_voices=6, patch=patch)."""
    dx7_patch = DX7Patch.from_syx(data, voice)
    amy_patch = AMYPatch.from_dx7(dx7_patch)
    amy.start_store_patch()
    amy_patch.send_to_AMY(reset=False)
    amy.stop_store_patch(patch)
    return dx7_patch.name


class AMYOscillator:
    def __init__(self):
        self.op_num = 0
        self.amp_levels = None
        self.amp_times = None
        self.op_amp = 0
        self.ampmodsens = 0
        self.frequency = 0
        self.freq_is_ratio = False

    @staticmethod
    def from_dx7_op(op):
        result = AMYOscillator()
        result.op_num = op.opnum
        result.amp_levels, result.amp_times = eg_to_bp(op.rates, op.levels)
        result.op_amp = 2 * dx7level_to_linear(op.opamp)
        if op.ratiotuning:
            result.frequency = coarse_fine_ratio(op.freq_coarse, op.freq_fine, op.freq_detune)
            result.freq_is_ratio = True
        else:
            result.frequency = coarse_fine_fixed_hz(op.freq_coarse, op.freq_fine, op.freq_detune)
            result.freq_is_ratio = False
        result.ampmodsens = float(op.ampmodsens)  # Don't know scaling, just 0/nonzero.
        return result

def fm_trunc(number):
    if(type(number)==float):
        return ('%.6f' % number).rstrip('0').rstrip('.')
    return str(number)

class AMYPatch:
    def __init__(self):
        self.oscs = None
        self.pitch_levels = None
        self.pitch_times = None
        self.algo = 0
        self.feedback = 0
        self.lfo_freq = 0
        self.lfo_delay = 0
        self.lfo_pitchmoddepth = 0
        self.lfo_ampmoddepth = 0
        self.lfo_waveform = 0
        self.name = ""
        self.amp_lfo_amp = 0
        self.pitch_lfo_amp = 0

    @staticmethod
    def from_dx7(dx7_patch):
        result = AMYPatch()
        result.oscs = []
        for op in dx7_patch.ops:
            result.oscs.append(AMYOscillator.from_dx7_op(op))
        result.pitch_levels, result.pitch_times = eg_to_bp_pitch(
            dx7_patch.pitch_rates, dx7_patch.pitch_levels)
        result.algo = dx7_patch.algo
        result.feedback = 0.00125 * (2 ** dx7_patch.feedback)
        result.lfo_freq = lfo_speed_to_hz(dx7_patch.lfospeed)
        result.lfo_delay = dx7_patch.lfodelay
        #result.lfo_pitchmoddepth = dx7_patch.lfopitchmoddepth
        result.lfo_ampmoddepth = dx7_patch.lfoampmoddepth
        result.lfo_waveform = lfo_wave(dx7_patch.lfowaveform)
        result.amp_lfo_amp = dx7level_to_linear(result.lfo_ampmoddepth)
        # With pitchmodsens at max (7), and PMD at max (99), the pitch mod is +/- 1 octave (24 semis range)
        # PMS 7 / PMD 50 is 12 semis range
        # PMS 7 / PMD 25 is 6 semis
        # PMS 7 / PMD 12 is 2 semis
        # PMS 7 / PMD 6 is 1 semi  .. really does look linear.
        # PMS 6 / PMD 99 is 14 semis range
        # PMS 5 / PMD 99 is ~8.5 semis
        # PMS 4 / PMD 99 is ~5.5 semis range
        # PMS 3 / PMD 99 is ~3.5
        # PMS 2 / PMD 99 is ~2 semi
        # PMS 1 / PMD 99 is ~1.5 semi
        # PMS 0 is no semi
        # Finally, matching K128 by ear, PMS 3/PDM 05 should give pitch_lfo_amp about 0.008.
        # So total range is about 1.7 ^ (PMS - 1) * (PMD / 99) semis
        # So scaling from +/-1 LFO to octaves is pow(1.7, (PMS - 1)) * (PMD / 99) / 12
        # 0.6 is a fudge factor.  Seems way too large for small values of PMD, so maybe PMD is exp-lin or smt
        result.pitch_lfo_amp = (
            0 if dx7_patch.pitchmodsens == 0
            else 0.6 * (1.7 ** (dx7_patch.pitchmodsens - 1)) * dx7_patch.lfopitchmoddepth / 1188.0
        )
        result.name = dx7_patch.name
        return result

    def send_to_AMY(self, reset=True):
        # Take a FM patch and output AMY commands to set up the patch.
        # Send amy.send(vel=1,osc=0,note=50) after
        t = fm_trunc
        if(reset): amy.reset()
        pitch_levels, pitch_times = self.pitch_levels, self.pitch_times
        pitchbp = "%d,%s,%d,%s,%d,%s,%d,%s,%d,%s" % (
            pitch_times[0], t(pitch_levels[0]), pitch_times[1], t(pitch_levels[1]),
            pitch_times[2], t(pitch_levels[2]), pitch_times[3], t(pitch_levels[3]),
            pitch_times[4], t(pitch_levels[4])
        )
        # Set up each operator.
        last_release_time = 0
        last_release_value = 0
        # Oscs: 0 is algo, 1 is LFO, 2-7 are ops 1-6
        main_osc = 0
        lfo_osc = 1
        # The osc of op0 (they go up from here)
        op0_osc = 2
        for op_num_from_0, osc in enumerate(self.oscs):
            osc_num = op0_osc + op_num_from_0
            amp_levels, amp_times = osc.amp_levels, osc.amp_times
            oscbp = "%d,%s,%d,%s,%d,%s,%d,%s,%d,%s" % (
                amp_times[0], t(amp_levels[0]), amp_times[1], t(amp_levels[1]),
                amp_times[2], t(amp_levels[2]), amp_times[3], t(amp_levels[3]),
                amp_times[4], t(amp_levels[4])
            )
            if(amp_times[4] > last_release_time):
                last_release_time = amp_times[4]
                last_release_value = amp_levels[4]
            #oscbpfmt = "%d,%s/%d,%s/%d,%s/%d,%s/%d,%s" % (
            #    amp_times[0], t(amp_levels[0]), amp_times[1], t(amp_levels[1]),
            #    amp_times[2], t(amp_levels[2]), amp_times[3], t(amp_levels[3]),
            #    amp_times[4], t(amp_levels[4])
            #)
            #print("osc %d (op %d) freq %.6f ratio %d env %s amp %.6f amp_mod %d" % \
            #      (osc_num, osc.op_num_from_0, osc.frequency, osc.freq_is_ratio, oscbpfmt,
            #       osc.op_amp, osc.ampmodsens))

            # Make them all in cosine phase, to be like DX7.  Important for slow oscs
            args = {"osc": osc_num,
                    "bp0": oscbp, "phase": 0.25}
            if osc.freq_is_ratio:
                args["ratio"] = t(osc.frequency)
            else:
                args["freq"] = t(osc.frequency)
            # TODO: we ignore intensity of amp mod sens, just on/off
            args.update({"mod_source": lfo_osc, "amp": "%s,0,0,1,0,%s" % (t(osc.op_amp), t(self.amp_lfo_amp * (osc.ampmodsens > 0)))})

            # We are _NOT_ updating operators with pitch bp, per dan tuesday 7/5 morning (but not monday 7/4 morning)
            #args.update({"bp1": pitchbp})

            amy.send(**args)

        # Set up the LFO x
        #print("osc %d amp lfo wave %d freq %f amp %f" % (
        #    lfo_osc, self.lfo_waveform, self.lfo_freq, 1)
        amy.send(osc=lfo_osc, wave=self.lfo_waveform, freq=t(self.lfo_freq),
                 amp=1, phase=0.25)

        #print("not used: lfo delay %d " % self.lfo_delay)

        #ampbp = "0,1,%d,%f" % (last_release_time, last_release_value)
        #print("osc 0 (main)  algo %d feedback %f pitchenv %s ampenv %s" % (
        #    self.algo, self.feedback, pitchbp, ampbp))
        amy.send(osc=main_osc, wave=amy.ALGO, algorithm=self.algo, feedback=t(self.feedback),
                 algo_source=",".join(str(o) for o in range(op0_osc, op0_osc + 6)),
                 #bp0=ampbp,
                 #bp1=pitchbp,
                 #freq="0,1,0,0,1,1",
                 bp0=pitchbp,
                 # bp1 is now ununsed.
                 amp="1,0,1,0,0,0",  # Turn off EG0 for amp
                 freq="0,1,0,1,0,%s" % t(self.pitch_lfo_amp),  # Turn on EG0 and LFO for freq
                 mod_source=lfo_osc)

def dx7level_to_linear(dx7level):
    """Map the dx7 0..99 levels to linear amplitude."""
    return 2 ** ((dx7level - 99) / 8)

def linear_to_dx7level(linear):
    """Map a linear amplitude to the dx7 0..99 scale."""
    return math.log(max(dx7level_to_linear(0), linear)) / _LOG2 * 8 + 99

def pitchval_to_ratio(pitchval):
    """Map 0..99 DX7 pitch vals (e.g. from pitch_env) into f0 ratios."""
    # Pitch map 0..99 actually becomes -128..127 via a symmetric map with 50->0, linear from 15 to 85, then
    # quadratic in the remainder.
    pitchsign = -1 + 2*(pitchval >= 50)
    semipitchval = float(abs(pitchval - 50))
    # Above (50 + 36), Quadratic to reach 127 at level 99.
    semipitchval += (semipitchval > 36) * (((semipitchval - 34)**2) * 93/225 - semipitchval + 34)
    # DX7 manual states pitchmod range is +/- 4 octaves, so 32 steps/oct sounds right.
    return 2 ** ((pitchsign * semipitchval) / 32)

def ratio_to_pitchval(ratio):
    semipitchval = 32 * math.log(ratio) / _LOG2
    pitchsign = -1 + 2*(semipitchval >= 0)
    semipitchval = abs(semipitchval)
    # Conditional treatment of outside -36 to 36.
    semipitchval += (semipitchval > 36) * (34 + math.sqrt(abs(semipitchval - 34) * (225/93)) - semipitchval)
    return 50 + pitchsign * semipitchval

def calc_loglin_eg_breakpoints(rates, levels, dx7_attacks=True,
                               rate_double_interval=6, rate_scale=0.5, rate_offset=0.5):
    """Convert the DX7 rates/levels into (time, target) pairs (for amy)"""
    if dx7_attacks:
        level_to_lin_fn = dx7level_to_linear
    else:
        level_to_lin_fn = pitchval_to_ratio
    # This is the part we precompute in fm.py to get breakpoints to send to amy.
    current_level = levels[-1]
    # EG at time 0 has final value from release.
    breakpoints = [(0, level_to_lin_fn(current_level))]

    MIN_LEVEL = 34
    ATTACK_RANGE = 75

    def level_to_attack_time(level, t_const):
        """Return the time at which a paradigmatic DX7 attack envelope will reach a level (0..99 range)"""
        # Return the t0 that solves level = MIN_LEVEL + ATTACK_RANGE * (1 - exp(-t0 / t_const))
        return -t_const * math.log((MIN_LEVEL + ATTACK_RANGE - max(MIN_LEVEL, level))/ATTACK_RANGE)

    for segment, (rate, target_level) in enumerate(zip(rates, levels)):
        release_segment = (segment == len(rates)-1)
        if dx7_attacks and target_level > current_level:   # Attack segment
            # The attack envelopes L(t) appear to be ~ 34 + 75 * (1 - exp(t / t_const)), starting from L = 34
            # i.e. they are rising exponentials (as in analog ADSR, but here in the log(amp) domain)
            # with an asymptote at 109 (i.e., 10 higher than the highest possible amp).
            # The time constant depends on the R (rate) parameter, and is well fit by:
            t_const = 0.008 * (2 ** ((65 - rate)/6))
            # Total time for this segment is t1 - t0 where t0 and t1 solve
            # effective_start = 34 + 75 * (1 - np.exp(-t0 / t_const)) = 109 - 75 exp(-t0 / t_c)
            # target_level = 34 + 75 * (1 - np.exp(-t1 / t_const)) = 109 - 75 exp(-t1 / t_c)
            # so t1 - t0 = -t_c * [log((34 + 75 - target_level)/75) - log((34 + 75 - effective_start)/75)]
            effective_start_level = max(current_level, MIN_LEVEL)
            t0 = level_to_attack_time(effective_start_level, t_const)
            segment_duration = level_to_attack_time(target_level, t_const) - t0
            #print("eff_st=", effective_start_level, "t_c=", t_const, "t0=", t0, "dur=", segment_duration)
            # Now amy's task will be to recover t0 and t_const from (time, target) pairs
        else:
            # Decay segment, or TRUE_EXPONENTIAL attack segment.
            direction = 1 if target_level > current_level else -1
            # "A falling segment takes 3.5 mins"
            # so delta = 99 in 210 seconds -> level_change_per_sec =  0.5
            # I think just offset everything by 0.5, avoids div0.
            level_change_per_sec = direction*(rate_offset + rate_scale * (2 ** (rate / rate_double_interval)))
            level_difference = target_level - current_level
            # Hack to cover for sustain = 0, release = 0 release segments which look like they should be zero long
            if release_segment and level_difference == 0:
                level_difference = direction * 60  # e.g. from a decayed level of 80 to zero.
                #print("** Goosing release amp")
            segment_duration = level_difference / level_change_per_sec
            #print("lcps=", level_change_per_sec, "dur=", segment_duration)
        breakpoints.append((segment_duration, level_to_lin_fn(target_level)))
        current_level = target_level
    return breakpoints

def eg_to_bp(egrate, eglevel, calc_eg_args={}):
    breakpoints = calc_loglin_eg_breakpoints(egrate, eglevel, **calc_eg_args)
    rates = []
    times = []
    for time, level in breakpoints:
        times.append(int(1000 * time))
        rates.append(level)
    return rates, times

def eg_to_bp_pitch(egrate, eglevel):
    # Additional args to make breakpoint calculation to the right thing for pitch.
    calc_pitch_eg_args = {'dx7_attacks': False, 'rate_double_interval': 20, 'rate_scale': 11, 'rate_offset': -6}
    return eg_to_bp(egrate, eglevel, calc_pitch_eg_args)

def coarse_fine_fixed_hz(coarse, fine, detune=7):
    coarse = coarse & 3
    return 10 ** (coarse + (fine + ((detune - 7) / 8)) / 100 )

def coarse_fine_ratio(coarse, fine, detune=7):
    coarse = coarse & 31
    if(coarse == 0):
        coarse = 0.5
    return coarse * (1 + (fine + ((detune - 7) / 8)) / 100)

def lfo_speed_to_hz(byte):
    # Measured values from TX802, linear fit by eye
    if byte == 0:
        return 0.064
    if byte <= 64:
        return byte / 6.0
    if byte <= 85:
        return byte - 64.0 * 5.0/6.0
    # Byte > 85
    return 31.67 + (byte - 85.0) * 1.33

def lfo_wave(byte):
    if byte > 5:
        return None
    return [
        amy.TRIANGLE, amy.SAW_DOWN, amy.SAW_UP,
        amy.PULSE, amy.SINE, amy.NOISE
    ][byte]


# Play a numpy array on an Apple Silicon mac without having to use an external library
# (sounddevice is currently broken on AS macs)
def play_np_array(np_array, samplerate=amy.AMY_SAMPLE_RATE):
    import wave, tempfile , os, struct
    tf = tempfile.NamedTemporaryFile()
    obj = wave.open(tf,'wb')
    obj.setnchannels(1) # mono
    obj.setsampwidth(2)
    obj.setframerate(samplerate)
    for i in range(len(np_array)):
        value = int(np_array[i] * 32767.0)
        data = struct.pack('<h', value)
        obj.writeframesraw( data )
    obj.close()
    os.system("afplay " + tf.name)
    tf.close()
