#!/usr/bin/env python3
"""Generate pcm_presets.generated.js from src/pcm_tiny.h.

Parses the pcm_map[] table (names from the trailing comments, wavetable
entries marked "WT") and emits window.AMY_WAVE_PRESETS, keyed by wave type
(PCM / WAVETABLE from amy/constants.py), for the AMYboard web editor's
preset knob UI.
"""
import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PCM_TINY_H = ROOT / "src" / "pcm_tiny.h"
AMY_CONSTANTS = ROOT / "amy" / "constants.py"
OUTPUT = ROOT / "src" / "pcm_presets.generated.js"

# One pcm_map[] row:  /* [11] WT */ {51053, 16384, 0, 16384, 69}, /* 111.WAV */
ENTRY_RE = re.compile(
    r'/\*\s*\[(\d+)\]\s*(\S+)\s*\*/\s*\{[^}]*\}\s*,\s*/\*\s*(.+?)\s*\*/'
)


def wave_constant(name: str) -> int:
    m = re.search(r'^%s\s*=\s*(\d+)' % name, AMY_CONSTANTS.read_text(), re.M)
    if not m:
        raise RuntimeError(f"Could not find {name} in amy/constants.py")
    return int(m.group(1))


def parse_presets(source: str):
    """Return {wave_number: [{name, value, wave}, ...]} from pcm_tiny.h."""
    pcm_wave = wave_constant("PCM")
    wavetable_wave = wave_constant("WAVETABLE")
    presets = {}
    for m in ENTRY_RE.finditer(source):
        index, marker, name = int(m.group(1)), m.group(2), m.group(3)
        wave = wavetable_wave if marker == "WT" else pcm_wave
        presets.setdefault(wave, []).append(
            {"name": name, "value": index, "wave": wave})
    if not presets:
        raise RuntimeError(f"No pcm_map entries found in {PCM_TINY_H}")
    return {str(k): v for k, v in presets.items()}


def generate_js(presets):
    body = json.dumps(presets, indent=2, sort_keys=True)
    return (
        "// AUTO-GENERATED by scripts/gen_pcm_presets_js.py — do not edit by hand.\n"
        "// Source: src/pcm_tiny.h\n"
        f"window.AMY_WAVE_PRESETS = {body};\n"
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true',
                    help='verify the committed output is up to date')
    opts = ap.parse_args()

    presets = parse_presets(PCM_TINY_H.read_text())
    js = generate_js(presets)
    if opts.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != js:
            print(f"stale {OUTPUT.relative_to(ROOT)} (run: python3 scripts/gen_pcm_presets_js.py)")
            sys.exit(1)
        print(f"{OUTPUT.relative_to(ROOT)} is up to date")
        return
    OUTPUT.write_text(js)
    n = sum(len(v) for v in presets.values())
    print(f"Generated {OUTPUT.relative_to(ROOT)} ({n} presets, {len(presets)} wave types)")


if __name__ == "__main__":
    main()
