USERMODULES_DIR := $(USERMOD_DIR)


# Add all C files to SRC_USERMOD.
SRC_USERMOD += $(USERMODULES_DIR)/algorithms.c
SRC_USERMOD += $(USERMODULES_DIR)/amy.c
SRC_USERMOD += $(USERMODULES_DIR)/envelope.c
SRC_USERMOD += $(USERMODULES_DIR)/examples.c
SRC_USERMOD += $(USERMODULES_DIR)/filters.c
SRC_USERMOD += $(USERMODULES_DIR)/oscillators.c
SRC_USERMOD += $(USERMODULES_DIR)/pcm.c
SRC_USERMOD += $(USERMODULES_DIR)/algorithms.c
SRC_USERMOD += $(USERMODULES_DIR)/partials.c
SRC_USERMOD += $(USERMODULES_DIR)/interp_partials.c
SRC_USERMOD += $(USERMODULES_DIR)/custom.c
SRC_USERMOD += $(USERMODULES_DIR)/delay.c
SRC_USERMOD += $(USERMODULES_DIR)/log2_exp2.c
SRC_USERMOD += $(USERMODULES_DIR)/patches.c
SRC_USERMOD += $(USERMODULES_DIR)/transfer.c
SRC_USERMOD += $(USERMODULES_DIR)/sequencer.c
SRC_USERMOD += $(USERMODULES_DIR)/libminiaudio-audio.c
SRC_USERMOD += $(USERMODULES_DIR)/esp32.c

CFLAGS_USERMOD += -I$(USERMODULES_DIR)

override CFLAGS_EXTRA += -DMODULE_AMY_ENABLED=1
