// Automatically generated by amy.headers.generate_gamma9001_headers()
// Map of the Gamma9001 drum banks over the raw int16 blob in drums.bin.
// The blob is provided at runtime via gamma9001_pcm (linked-in on web,
// mmapped from a flash partition on ESP32-S3). Only used when GAMMA9001
// is defined.
#ifndef __PCM_GAMMA9001_H
#define __PCM_GAMMA9001_H
#define GAMMA9001_PRESET_BASE 256
#define GAMMA9001_NUM_SAMPLES 136
#define GAMMA9001_SAMPLE_RATE 22050
#define GAMMA9001_BIN_FRAMES 1867894
const pcm_map_t gamma9001_map[GAMMA9001_NUM_SAMPLES] PROGMEM = {
    /* [0] preset 256 */ {0, 18889, 0, 0, 60}, /* tr909: 909BD */
    /* [1] preset 257 */ {18889, 23596, 0, 0, 60}, /* tr909: 909BD-LO */
    /* [2] preset 258 */ {42485, 21180, 0, 0, 60}, /* tr909: 909CLAP */
    /* [3] preset 259 */ {63665, 21326, 0, 0, 60}, /* tr909: 909CRASH */
    /* [4] preset 260 */ {84991, 2980, 0, 0, 60}, /* tr909: 909HH */
    /* [5] preset 261 */ {87971, 4871, 0, 0, 60}, /* tr909: 909HH-LONG */
    /* [6] preset 262 */ {92842, 1341, 0, 0, 60}, /* tr909: 909HH-SHORT */
    /* [7] preset 263 */ {94183, 11709, 0, 0, 60}, /* tr909: 909OH */
    /* [8] preset 264 */ {105892, 11716, 0, 0, 60}, /* tr909: 909OH-LONG */
    /* [9] preset 265 */ {117608, 8755, 0, 0, 60}, /* tr909: 909OH-SHORT */
    /* [10] preset 266 */ {126363, 23365, 0, 0, 60}, /* tr909: 909RIDE */
    /* [11] preset 267 */ {149728, 17291, 0, 0, 60}, /* tr909: 909RIM */
    /* [12] preset 268 */ {167019, 5659, 0, 0, 60}, /* tr909: 909SD */
    /* [13] preset 269 */ {172678, 5448, 0, 0, 60}, /* tr909: 909SD-SHORT */
    /* [14] preset 270 */ {178126, 24319, 0, 0, 60}, /* tr909: 909TOM-HI */
    /* [15] preset 271 */ {202445, 20912, 0, 0, 60}, /* tr909: 909TOM-LO */
    /* [16] preset 272 */ {223357, 23831, 0, 0, 60}, /* tr909: 909TOM-MID */
    /* [17] preset 273 */ {247188, 2944, 0, 0, 60}, /* linn9000: BassDrum 1 */
    /* [18] preset 274 */ {250132, 4410, 0, 0, 60}, /* linn9000: Bongo 3 */
    /* [19] preset 275 */ {254542, 5376, 0, 0, 60}, /* linn9000: CowBell 1 */
    /* [20] preset 276 */ {259918, 27235, 0, 0, 60}, /* linn9000: Cymbal 2 */
    /* [21] preset 277 */ {287153, 1600, 0, 0, 60}, /* linn9000: HiHat Closed 3 */
    /* [22] preset 278 */ {288753, 10176, 0, 0, 60}, /* linn9000: HiHat Open 2 */
    /* [23] preset 279 */ {298929, 3264, 0, 0, 60}, /* linn9000: RimShoot 1 */
    /* [24] preset 280 */ {302193, 4544, 0, 0, 60}, /* linn9000: SnareDrum 1 */
    /* [25] preset 281 */ {306737, 5824, 0, 0, 60}, /* linn9000: Taburine 1 */
    /* [26] preset 282 */ {312561, 4224, 0, 0, 60}, /* linn9000: TomTom 2 */
    /* [27] preset 283 */ {316785, 998, 0, 0, 60}, /* mr12: MR-12#HHC */
    /* [28] preset 284 */ {317783, 9424, 0, 0, 60}, /* mr12: MR-12#HHO */
    /* [29] preset 285 */ {327207, 7777, 0, 0, 60}, /* mr12: MR-12#KICK */
    /* [30] preset 286 */ {334984, 4256, 0, 0, 60}, /* mr12: MR-12#SNR */
    /* [31] preset 287 */ {339240, 870, 0, 0, 60}, /* synthetics: Metallic 09 */
    /* [32] preset 288 */ {340110, 209, 0, 0, 60}, /* synthetics: Metallic 16 */
    /* [33] preset 289 */ {340319, 1506, 0, 0, 60}, /* synthetics: Static 07 */
    /* [34] preset 290 */ {341825, 321, 0, 0, 60}, /* synthetics: Wooden 01 */
    /* [35] preset 291 */ {342146, 295, 0, 0, 60}, /* synthetics: Wooden 02 */
    /* [36] preset 292 */ {342441, 3050, 0, 0, 60}, /* synthetics: Wooden 03 */
    /* [37] preset 293 */ {345491, 620, 0, 0, 60}, /* synthetics: BD 03 */
    /* [38] preset 294 */ {346111, 3292, 0, 0, 60}, /* synthetics: BD 04 */
    /* [39] preset 295 */ {349403, 1440, 0, 0, 60}, /* synthetics: BD 07 */
    /* [40] preset 296 */ {350843, 11008, 0, 0, 60}, /* synthetics: Tokyo Burst bd */
    /* [41] preset 297 */ {361851, 4542, 0, 0, 60}, /* synthetics: Tokyo Deep bd */
    /* [42] preset 298 */ {366393, 9004, 0, 0, 60}, /* synthetics: Tokyo Jet bd */
    /* [43] preset 299 */ {375397, 14272, 0, 0, 60}, /* synthetics: Tokyo Space */
    /* [44] preset 300 */ {389669, 7962, 0, 0, 60}, /* synthetics: Hizz 06 */
    /* [45] preset 301 */ {397631, 3616, 0, 0, 60}, /* synthetics: Pew 03 */
    /* [46] preset 302 */ {401247, 1709, 0, 0, 60}, /* synthetics: Boink 02 */
    /* [47] preset 303 */ {402956, 9472, 0, 0, 60}, /* synthetics: Boink 04 */
    /* [48] preset 304 */ {412428, 2048, 0, 0, 60}, /* synthetics: Blop 01 */
    /* [49] preset 305 */ {414476, 1554, 0, 0, 60}, /* synthetics: Blop 02 */
    /* [50] preset 306 */ {416030, 812, 0, 0, 60}, /* synthetics: Click 05 */
    /* [51] preset 307 */ {416842, 329, 0, 0, 60}, /* synthetics: Click 06 */
    /* [52] preset 308 */ {417171, 456, 0, 0, 60}, /* synthetics: Click 07 */
    /* [53] preset 309 */ {417627, 331, 0, 0, 60}, /* synthetics: Click 08 */
    /* [54] preset 310 */ {417958, 381, 0, 0, 60}, /* synthetics: Click 09 */
    /* [55] preset 311 */ {418339, 14627, 0, 0, 35}, /* power: Real Kick */
    /* [56] preset 312 */ {432966, 15343, 0, 0, 36}, /* power: Metal Kick */
    /* [57] preset 313 */ {448309, 19776, 0, 0, 37}, /* power: Side Stick */
    /* [58] preset 314 */ {468085, 23780, 0, 0, 38}, /* power: Power Snare */
    /* [59] preset 315 */ {491865, 21521, 0, 0, 39}, /* power: Hand Claps */
    /* [60] preset 316 */ {513386, 24220, 0, 0, 40}, /* power: Gated Snare */
    /* [61] preset 317 */ {537606, 21796, 0, 0, 41}, /* power: Process Tom 1 */
    /* [62] preset 318 */ {559402, 22016, 0, 0, 42}, /* power: Tight HiHat */
    /* [63] preset 319 */ {581418, 20418, 0, 0, 43}, /* power: Process Tom 2 */
    /* [64] preset 320 */ {601836, 22272, 0, 0, 44}, /* power: Pedal HiHat */
    /* [65] preset 321 */ {624108, 21653, 0, 0, 45}, /* power: Process Tom 3 */
    /* [66] preset 322 */ {645761, 24448, 0, 0, 46}, /* power: Open HiHat */
    /* [67] preset 323 */ {670209, 22726, 0, 0, 47}, /* power: Process Tom 4 */
    /* [68] preset 324 */ {692935, 33024, 0, 0, 48}, /* power: Process Tom 5 */
    /* [69] preset 325 */ {725959, 63073, 0, 0, 49}, /* power: Crash Cymbal */
    /* [70] preset 326 */ {789032, 25856, 0, 0, 50}, /* power: Process Tom 6 */
    /* [71] preset 327 */ {814888, 24379, 0, 0, 51}, /* power: Ride Edge */
    /* [72] preset 328 */ {839267, 18630, 0, 0, 53}, /* power: Ride Cup */
    /* [73] preset 329 */ {857897, 21040, 0, 0, 55}, /* power: Splash Cymbal */
    /* [74] preset 330 */ {878937, 17242, 0, 0, 56}, /* power: Cowbell */
    /* [75] preset 331 */ {896179, 6128, 0, 0, 60}, /* percussion: African Conga 001 */
    /* [76] preset 332 */ {902307, 6831, 0, 0, 60}, /* percussion: African Conga 002 */
    /* [77] preset 333 */ {909138, 3963, 0, 0, 60}, /* percussion: African Conga 003 */
    /* [78] preset 334 */ {913101, 3467, 0, 0, 60}, /* percussion: African Conga 004 */
    /* [79] preset 335 */ {916568, 4500, 0, 0, 60}, /* percussion: Bongo 001 */
    /* [80] preset 336 */ {921068, 1964, 0, 0, 60}, /* percussion: Bongo 002 */
    /* [81] preset 337 */ {923032, 4022, 0, 0, 60}, /* percussion: Bongo 003 */
    /* [82] preset 338 */ {927054, 4780, 0, 0, 60}, /* percussion: Bongo 004 */
    /* [83] preset 339 */ {931834, 1241, 0, 0, 60}, /* percussion: Bongo 005 */
    /* [84] preset 340 */ {933075, 3774, 0, 0, 60}, /* percussion: Bongo 006 */
    /* [85] preset 341 */ {936849, 3892, 0, 0, 60}, /* percussion: Bongo 007 */
    /* [86] preset 342 */ {940741, 6305, 0, 0, 60}, /* percussion: Conga 001 */
    /* [87] preset 343 */ {947046, 2136, 0, 0, 60}, /* percussion: Conga 002 */
    /* [88] preset 344 */ {949182, 2456, 0, 0, 60}, /* percussion: Conga 003 */
    /* [89] preset 345 */ {951638, 2992, 0, 0, 60}, /* percussion: Conga 004 */
    /* [90] preset 346 */ {954630, 3167, 0, 0, 60}, /* percussion: Conga 005 */
    /* [91] preset 347 */ {957797, 2828, 0, 0, 60}, /* percussion: Conga 006 */
    /* [92] preset 348 */ {960625, 40282, 0, 0, 60}, /* percussion: Digeridoo */
    /* [93] preset 349 */ {1000907, 8485, 0, 0, 60}, /* percussion: Kanu 001 */
    /* [94] preset 350 */ {1009392, 6054, 0, 0, 60}, /* percussion: Noice Kick */
    /* [95] preset 351 */ {1015446, 3952, 0, 0, 60}, /* percussion: Old Snare */
    /* [96] preset 352 */ {1019398, 3748, 0, 0, 60}, /* percussion: Simple Shaker */
    /* [97] preset 353 */ {1023146, 3364, 0, 0, 60}, /* percussion: Simple Shaker 002 */
    /* [98] preset 354 */ {1026510, 20012, 0, 0, 60}, /* percussion: Sitar */
    /* [99] preset 355 */ {1046522, 5248, 0, 0, 60}, /* percussion: Strings Tutti 001 */
    /* [100] preset 356 */ {1051770, 9472, 0, 0, 60}, /* percussion: Strings Tutti 002 */
    /* [101] preset 357 */ {1061242, 25739, 0, 0, 60}, /* percussion: Strings sweep */
    /* [102] preset 358 */ {1086981, 3149, 0, 0, 60}, /* percussion: Tabla 001 */
    /* [103] preset 359 */ {1090130, 3437, 0, 0, 60}, /* percussion: Tabla 002 */
    /* [104] preset 360 */ {1093567, 3922, 0, 0, 60}, /* percussion: Tabla 003 */
    /* [105] preset 361 */ {1097489, 4837, 0, 0, 60}, /* percussion: Tamb 001 */
    /* [106] preset 362 */ {1102326, 2916, 0, 0, 60}, /* percussion: Tamb 003 */
    /* [107] preset 363 */ {1105242, 5645, 0, 0, 60}, /* percussion: Tamb 004 */
    /* [108] preset 364 */ {1110887, 7258, 0, 0, 60}, /* percussion: Tamp 002 */
    /* [109] preset 365 */ {1118145, 7248, 0, 0, 60}, /* percussion: Timbales 001 */
    /* [110] preset 366 */ {1125393, 2334, 0, 0, 60}, /* percussion: Timbales 002 */
    /* [111] preset 367 */ {1127727, 4572, 0, 0, 60}, /* percussion: Timbales 003 */
    /* [112] preset 368 */ {1132299, 5901, 0, 0, 60}, /* percussion: Timbales 004 */
    /* [113] preset 369 */ {1138200, 22716, 0, 0, 60}, /* percussion: Timpani 001 */
    /* [114] preset 370 */ {1160916, 45478, 0, 0, 60}, /* percussion: Timpani 002 */
    /* [115] preset 371 */ {1206394, 4046, 0, 0, 60}, /* percussion: Triangle 001 */
    /* [116] preset 372 */ {1210440, 10728, 0, 0, 60}, /* percussion: Triangle 002 */
    /* [117] preset 373 */ {1221168, 4837, 0, 0, 60}, /* percussion: Untitled */
    /* [118] preset 374 */ {1226005, 2314, 0, 0, 60}, /* percussion: Wistle 001 */
    /* [119] preset 375 */ {1228319, 3095, 0, 0, 60}, /* acoustic: Tambourine Short */
    /* [120] preset 376 */ {1231414, 2560, 0, 0, 60}, /* acoustic: Shaker Short */
    /* [121] preset 377 */ {1233974, 704, 0, 0, 60}, /* acoustic: Shaker Tiny */
    /* [122] preset 378 */ {1234678, 54912, 0, 0, 60}, /* extras: JCave */
    /* [123] preset 379 */ {1289590, 36864, 0, 0, 60}, /* extras: Laser */
    /* [124] preset 380 */ {1326454, 45056, 0, 0, 60}, /* extras: Mach3 */
    /* [125] preset 381 */ {1371510, 36096, 0, 0, 60}, /* extras: Silver */
    /* [126] preset 382 */ {1407606, 56128, 0, 0, 60}, /* extras: Vibrablib */
    /* [127] preset 383 */ {1463734, 30400, 0, 0, 60}, /* extras: HeHa */
    /* [128] preset 384 */ {1494134, 43392, 0, 0, 60}, /* extras: HiHi */
    /* [129] preset 385 */ {1537526, 106304, 0, 0, 60}, /* extras: Dim Future */
    /* [130] preset 386 */ {1643830, 26560, 0, 0, 60}, /* extras: Smiling */
    /* [131] preset 387 */ {1670390, 30528, 0, 0, 60}, /* extras: Ana Strings */
    /* [132] preset 388 */ {1700918, 12672, 0, 0, 60}, /* extras: BassRec */
    /* [133] preset 389 */ {1713590, 16192, 0, 0, 60}, /* extras: Xox */
    /* [134] preset 390 */ {1729782, 114688, 0, 0, 60}, /* extras: Beach */
    /* [135] preset 391 */ {1844470, 23424, 0, 0, 60}, /* extras: Narrow */
};

#endif  // __PCM_GAMMA9001_H
