// Automatically generated by amy.headers.generate_pcm_header()
#ifndef __PCM_H
#define __PCM_H
#define PCM_AMY_SAMPLE_RATE 22050
#define PCM_BASE_SAMPLES 11
#define PCM_BASE_LENGTH 51053
#if defined(AMY_WAVETABLE)
#define PCM_WAVETABLE_BASE PCM_BASE_SAMPLES
#define PCM_WAVETABLE_SAMPLES 5
#define PCM_WAVETABLE_LEN 16384
#define PCM_LENGTH (PCM_BASE_LENGTH + (PCM_WAVETABLE_SAMPLES * PCM_WAVETABLE_LEN))
#define PCM_MAP_ENTRIES (PCM_BASE_SAMPLES + PCM_WAVETABLE_SAMPLES)
#else
#define PCM_WAVETABLE_BASE PCM_BASE_SAMPLES
#define PCM_WAVETABLE_SAMPLES 0
#define PCM_WAVETABLE_LEN 0
#define PCM_LENGTH PCM_BASE_LENGTH
#define PCM_MAP_ENTRIES PCM_BASE_SAMPLES
#endif
#include "pcm_samples_tiny.h"
const uint16_t pcm_samples = PCM_MAP_ENTRIES;
const uint16_t pcm_wavetable_base = PCM_WAVETABLE_BASE;
const uint16_t pcm_wavetable_samples = PCM_WAVETABLE_SAMPLES;
const uint32_t pcm_wavetable_len = PCM_WAVETABLE_LEN;
const pcm_map_t pcm_map[PCM_MAP_ENTRIES] PROGMEM = {
/* [0] 0 */ {0, 707, 342, 684, 89}, /* 808-MARACA-D */
    /* [1] 3 */ {707, 8186, 4282, 7439, 39}, /* 808-KIK 4-D */
    /* [2] 8 */ {8893, 2766, 1377, 2744, 45}, /* 808-SNR 4-D */
    /* [3] 11 */ {11659, 1311, 898, 1288, 52}, /* 808-SNR 7-D */
    /* [4] 14 */ {12970, 2276, 1164, 2254, 51}, /* 808-SNR 10D */
    /* [5] 16 */ {15246, 2872, 1430, 2849, 41}, /* 808-SNR 12-D */
    /* [6] 17 */ {18118, 1751, 888, 1728, 53}, /* 808-C-HAT1-D */
    /* [7] 18 */ {19869, 15400, 7815, 15377, 56}, /* 808-O-HAT1-D */
    /* [8] 20 */ {35269, 8995, 4588, 8973, 61}, /* 808-LTOM M-D */
    /* [9] 23 */ {44264, 3027, 1504, 3004, 94}, /* 808-DRYCLP-D */
    /* [10] 25 */ {47291, 3762, 22, 1871, 69}, /* 808-CWBELL-D */
#if defined(AMY_WAVETABLE)
    /* [11] WT */ {51053, 16384, 0, 16384, 69}, /* 111.WAV */
    /* [12] WT */ {67437, 16384, 0, 16384, 69}, /* BRAIDS01.WAV */
    /* [13] WT */ {83821, 16384, 0, 16384, 69}, /* PPG_WA00.WAV */
    /* [14] WT */ {100205, 16384, 0, 16384, 69}, /* SINE2SAW.WAV */
    /* [15] WT */ {116589, 16384, 0, 16384, 69}, /* VIRAL.WAV */
#endif
};

#endif  // __PCM_H
