// Automatically generated by amy.headers.generate_gamma9001_headers()
#ifndef __PCM_H
#define __PCM_H
#define PCM_AMY_SAMPLE_RATE 22050
#define PCM_BASE_SAMPLES 19
#define PCM_BASE_LENGTH 188358
#if defined(AMY_WAVETABLE)
#define PCM_WAVETABLE_BASE PCM_BASE_SAMPLES
#define PCM_WAVETABLE_SAMPLES 5
#define PCM_WAVETABLE_LEN 16384
#define PCM_LENGTH (PCM_BASE_LENGTH + (PCM_WAVETABLE_SAMPLES * PCM_WAVETABLE_LEN))
#define PCM_MAP_ENTRIES (PCM_BASE_SAMPLES + PCM_WAVETABLE_SAMPLES)
#else
#define PCM_WAVETABLE_BASE PCM_BASE_SAMPLES
#define PCM_WAVETABLE_SAMPLES 0
#define PCM_WAVETABLE_LEN 0
#define PCM_LENGTH PCM_BASE_LENGTH
#define PCM_MAP_ENTRIES PCM_BASE_SAMPLES
#endif
#include "pcm_samples_gamma808.h"
const uint16_t pcm_samples = PCM_MAP_ENTRIES;
const uint16_t pcm_wavetable_base = PCM_WAVETABLE_BASE;
const uint16_t pcm_wavetable_samples = PCM_WAVETABLE_SAMPLES;
const uint32_t pcm_wavetable_len = PCM_WAVETABLE_LEN;
const pcm_map_t pcm_map[PCM_MAP_ENTRIES] PROGMEM = {
    /* [0] */ {0, 68832, 0, 0, 60}, /* TR-808 Bass Drum 1 */
    /* [1] */ {68832, 27366, 0, 0, 60}, /* TR-808 Bass Drum 2 */
    /* [2] */ {96198, 18048, 0, 0, 60}, /* TR-808 Bass Drum 3 */
    /* [3] */ {114246, 3208, 0, 0, 60}, /* TR-808 Clap */
    /* [4] */ {117454, 1032, 0, 0, 60}, /* TR-808 Clave */
    /* [5] */ {118486, 3328, 0, 0, 60}, /* TR-808 Conga Hi */
    /* [6] */ {121814, 6784, 0, 0, 60}, /* TR-808 Conga Lo */
    /* [7] */ {128598, 3995, 0, 0, 60}, /* TR-808 Conga Mid */
    /* [8] */ {132593, 7616, 0, 0, 60}, /* TR-808 Cowbell */
    /* [9] */ {140209, 2210, 0, 0, 60}, /* TR-808 HiHat Closed */
    /* [10] */ {142419, 11840, 0, 0, 60}, /* TR-808 HiHat Open */
    /* [11] */ {154259, 755, 0, 0, 60}, /* TR-808 Shaker */
    /* [12] */ {155014, 2767, 0, 0, 45}, /* TR-808 Snare 1 */
    /* [13] */ {157781, 1312, 0, 0, 52}, /* TR-808 Snare 2 */
    /* [14] */ {159093, 2873, 0, 0, 41}, /* TR-808 Snare 3 */
    /* [15] */ {161966, 292, 0, 0, 90}, /* TR-808 Rimshot */
    /* [16] */ {162258, 8996, 0, 0, 61}, /* TR-808 Tom Lo */
    /* [17] */ {171254, 4708, 0, 0, 67}, /* TR-808 Tom Hi */
    /* [18] */ {175962, 12396, 0, 0, 59}, /* TR-808 Cymbal */
#if defined(AMY_WAVETABLE)
    /* [19] WT */ {188358, 16384, 0, 16384, 69}, /* 111.WAV */
    /* [20] WT */ {204742, 16384, 0, 16384, 69}, /* BRAIDS01.WAV */
    /* [21] WT */ {221126, 16384, 0, 16384, 69}, /* PPG_WA00.WAV */
    /* [22] WT */ {237510, 16384, 0, 16384, 69}, /* SINE2SAW.WAV */
    /* [23] WT */ {253894, 16384, 0, 16384, 69}, /* VIRAL.WAV */
#endif
};

#endif  // __PCM_H
